// export enum Nation {
//   american = 'american',
//   arabian = 'arabian',
//   assyrian = 'assyrian',
//   austrian = 'austrian',
//   aztec = 'aztec',
//   babylonian = 'babylonian',
//   brazilian = 'brazilian', 
//   byzantine = 'byzantine',
//   carthaginian = 'carthaginian',
//   celtic = 'celtic',
//   chinese = 'chinese',
//   danish = 'danish',
//   dutch = 'dutch',
//   egyptian = 'egyptian',
//   english = 'english',
//   ethiopian = 'ethiopian',
//   french = 'french',
//   german = 'german',
//   greek = 'greek',
//   hunnic = 'hunnic',
//   incan = 'incan',
//   indian = 'indian',
//   indonesian = 'indonesian',
//   iroquois = 'iroquois',
//   japanese = 'japanese',
//   korean = 'korean',
//   mayan = 'mayan',
//   mongolian = 'mongolian',
//   moroccan = 'moroccan',
//   ottoman = 'ottoman',
//   persian = 'persian',
//   polish = 'polish',
//   polynesian = 'polynesian',
//   portuguese = 'portuguese',
//   roman = 'roman',
//   russian = 'russian',
//   shoshone = 'shoshone',
//   siamese = 'siamese',
//   songhai = 'songhai',
//   spanish = 'spanish',
//   swedish = 'swedish',
//   venetian = 'venetian',
//   zulu = 'zulu',
// }

export interface Nation {
  name: string;
  coeff: number;
}